/**
 * Cloudinary Image Registry
 * All images are hosted on Cloudinary CDN
 */

export const CLOUDINARY_IMAGES = {
  "achievement_green_india_hackathon.jpg.jpeg": "https://res.cloudinary.com/uesw5nai/image/upload/v1789725813/rym_website/achievement_green_india_hackathon_jpg.jpg",
  "SmartSystems_HP.gif": "https://res.cloudinary.com/uesw5nai/image/upload/v1789725815/rym_website/SmartSystems_HP.gif",
  "Technologies.gif": "https://res.cloudinary.com/uesw5nai/image/upload/v1789725818/rym_website/Technologies.gif",
  "Ultron.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789725820/rym_website/Ultron.png",
  "achievement_anyeshana.jpeg": "https://res.cloudinary.com/uesw5nai/image/upload/v1789725825/rym_website/achievement_anyeshana.jpg",
  "achievement_great_india_hackathon.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789725826/rym_website/achievement_great_india_hackathon.jpg",
  "achievement_hackaithon_1.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789725829/rym_website/achievement_hackaithon_1.jpg",
  "achievement_hackaithon_2.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789725830/rym_website/achievement_hackaithon_2.jpg",
  "achievement_hackaithon_3.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789725832/rym_website/achievement_hackaithon_3.jpg",
  "achievement_hackaithon_4.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789725834/rym_website/achievement_hackaithon_4.jpg",
  "achievement_hack_krmu.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789725836/rym_website/achievement_hack_krmu.jpg",
  "achievement_hardwar_2.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789725837/rym_website/achievement_hardwar_2.jpg",
  "achievement_iit_roorkee_grant.jpg": "https://res.cloudinary.com/uesw5nai/image/upload/v1789725881/rym_website/achievement_iit_roorkee_grant.png",
  "Achievement_Image.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789725923/rym_website/Achievement_Image.png",
  "achievement_innospark.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789725926/rym_website/achievement_innospark.jpg",
  "achievement_kpit_gold_award.jpg": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726555/rym_website/achievement_kpit_gold_award.jpg",
  "achievement_kr_expo_1.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726020/rym_website/achievement_kr_expo_1.jpg",
  "achievement_kr_expo_2.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726021/rym_website/achievement_kr_expo_2.jpg",
  "achievement_kr_expo_3.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726023/rym_website/achievement_kr_expo_3.jpg",
  "achievement_lead_3rd_prize.jpg": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726025/rym_website/achievement_lead_3rd_prize.jpg",
  "achievement_lead_conclave.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726026/rym_website/achievement_lead_conclave.jpg",
  "achievement_nrl_5th_prize.jpg": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726567/rym_website/achievement_nrl_5th_prize.jpg",
  "achievement_nrl_award_ceremony.jpg": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726581/rym_website/achievement_nrl_award_ceremony.jpg",
  "achievement_nrl_group_photo.jpg": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726233/rym_website/achievement_nrl_group_photo.jpg",
  "achievement_parul_hackverse.jpg": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726261/rym_website/achievement_parul_hackverse.jpg",
  "achievement_sharda_hackathon.jpg.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726262/rym_website/achievement_sharda_hackathon_jpg.jpg",
  "AIDrive.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726263/rym_website/AIDrive.png",
  "AIS.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726264/rym_website/AIS.png",
  "AryanSani.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726278/rym_website/AryanSani.png",
  "carrer1.jpg": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726279/rym_website/carrer1.jpg",
  "carrer2.jpg": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726280/rym_website/carrer2.jpg",
  "carrer3.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726287/rym_website/carrer3.png",
  "CCTV.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726291/rym_website/CCTV.png",
  "DivyaDhistri.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726298/rym_website/DivyaDhistri.png",
  "EV-integration.jpg": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726300/rym_website/EV-integration.jpg",
  "EV_Charging.jpeg": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726309/rym_website/EV_Charging.jpg",
  "Favicon.svg": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726310/rym_website/Favicon.svg",
  "IDP.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726312/rym_website/IDP.png",
  "image copy.jpeg": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726314/rym_website/image_copy.jpg",
  "image.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726330/rym_website/image.png",
  "Intelexa.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726333/rym_website/Intelexa.png",
  "join.jpg": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726336/rym_website/join.jpg",
  "Logo.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726337/rym_website/Logo.png",
  "minimal_testimonials.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726339/rym_website/minimal_testimonials.jpg",
  "partner_acl.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726340/rym_website/partner_acl.jpg",
  "partner_bm.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726341/rym_website/partner_bm.jpg",
  "partner_boxfox.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726342/rym_website/partner_boxfox.jpg",
  "partner_bworth.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726342/rym_website/partner_bworth.jpg",
  "partner_closetrush.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726343/rym_website/partner_closetrush.jpg",
  "partner_gkm.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726344/rym_website/partner_gkm.jpg",
  "partner_golcha_associated.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726345/rym_website/partner_golcha_associated.jpg",
  "partner_iit_roorkee.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726346/rym_website/partner_iit_roorkee.jpg",
  "partner_inventis_labs.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726347/rym_website/partner_inventis_labs.jpg",
  "partner_jk_cement.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726347/rym_website/partner_jk_cement.jpg",
  "partner_jsw.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726348/rym_website/partner_jsw.jpg",
  "partner_khannas_supreme.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726349/rym_website/partner_khannas_supreme.jpg",
  "partner_leymen.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726350/rym_website/partner_leymen.jpg",
  "partner_rk_marble.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726350/rym_website/partner_rk_marble.jpg",
  "partner_seemee.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726351/rym_website/partner_seemee.jpg",
  "partner_shree_cement.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726352/rym_website/partner_shree_cement.jpg",
  "partner_sovra.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726353/rym_website/partner_sovra.jpg",
  "partner_synchronous.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726353/rym_website/partner_synchronous.jpg",
  "partner_vegavruddhi.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726354/rym_website/partner_vegavruddhi.jpg",
  "Processors.jpeg": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726369/rym_website/Processors.jpg",
  "product.jpeg": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726877/rym_website/product.jpg",
  "product.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726888/rym_website/product.png",
  "product_divyadrishti_ai.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726378/rym_website/product_divyadrishti_ai.jpg",
  "product_haier_qc.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726379/rym_website/product_haier_qc.jpg",
  "product_nexora_one.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726380/rym_website/product_nexora_one.jpg",
  "product_vyara_tiles.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726381/rym_website/product_vyara_tiles.jpg",
  "Renox.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726386/rym_website/Renox.png",
  "Saurav.jpeg": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726388/rym_website/Saurav.jpg",
  "sdg (1).png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726389/rym_website/sdg__1_.png",
  "sdg (2).png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726390/rym_website/sdg__2_.png",
  "sdg (3).png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726390/rym_website/sdg__3_.png",
  "sdg (4).png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726392/rym_website/sdg__4_.png",
  "sdg.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726392/rym_website/sdg.png",
  "Section_Image.jpeg": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726922/rym_website/Section_Image.jpg",
  "SHAS.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726924/rym_website/SHAS.png",
  "testimonials (1).jpeg": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726925/rym_website/testimonials__1_.jpg",
  "testimonials (1).jpg": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726927/rym_website/testimonials__1_.jpg",
  "testimonials (2).jpg": "https://res.cloudinary.com/uesw5nai/image/upload/v1789726936/rym_website/testimonials__2_.jpg",
  "testimonials.jpeg": "https://res.cloudinary.com/uesw5nai/image/upload/v1789727013/rym_website/testimonials.jpg",
  "testimonials.jpg": "https://res.cloudinary.com/uesw5nai/image/upload/v1789727027/rym_website/testimonials.jpg",
  "testimonials.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789727032/rym_website/testimonials.png",
  "testimonials_banner_art.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789727044/rym_website/testimonials_banner_art.jpg",
  "tides_iit_roorkee.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789727049/rym_website/tides_iit_roorkee.jpg",
  "Tranform_Your_Energy_Systems_for_Tomorrows_Demands.jpeg": "https://res.cloudinary.com/uesw5nai/image/upload/v1789727059/rym_website/Tranform_Your_Energy_Systems_for_Tomorrows_Demands.jpg",
  "Weighbridge_AI.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789727178/rym_website/Weighbridge_AI.png",
  "YR.png": "https://res.cloudinary.com/uesw5nai/image/upload/v1789727182/rym_website/YR.png"
};

export const getCloudinaryImage = (filename) => {
  return CLOUDINARY_IMAGES[filename] || filename;
};

export default CLOUDINARY_IMAGES;
